Use Node 20 version
visable-dev/gh-action-terragrunt-report pull request #11
Opened 2024-04-17 09:30 UTC by hernanvicente

With GitHub Actions transitioning from Node 16 to 20, some applications using this module receive warnings. For us, Panda, our statistics application GitHub workflows show the following warnings:

![iac_actions_run_warnings](https://github.com/visable-dev/gh-action-terragrunt-report/assets/229974/73df5dc2-75e4-435b-9da1-ecae2d9aa7c3)

This PR tries to update Node and some packages to bear this problem.

2024-04-24 06:01 UTC, littldr requested changes
Thanks for this contribution, @hernanvicente!

I requested a single change, but I'm happy to merge and release it asap. :)

2024-04-24 06:01 UTC, littldr commented on dist/index.js
Could you please remove the dist file from your PR? It will be automatically generated on release.

2024-04-26 11:08 UTC, hernanvicente commented on dist/index.js
I removed the folder. It was a leftover that helped me test the update =)

2024-04-26 11:08 UTC, hernanvicente commented
One thing more was pending, and I just updated the release workflow. This was using 'JasonEtco/build-and-tag-action@v1', which relies on Node 16. I forked the code and released a version with Node 20. The action now uses the new repository.

2024-04-29 07:30 UTC, littldr approved these changes
Great. Thanks! :)

2024-04-29 07:31 UTC, merged